name: babel2msa
channels:
  - conda-forge
  - anaconda
dependencies:
  - python >=3.9,<3.13
  - pypythia
  - ete3
  - legacy-cgi
  - anaconda::jpype1
  - tabulate
  - biopython
  - pip
  - pip:
    - epitran
    - ipatok
    - lingpy>=2.6.13
    - pyglottolog
    - iso639-lang
    - pythialabelgenerator
